### ISSUE TITLE
Why eset finding virus 10 second i launching application ?

### ISSUE THREAD

**Issue by ReconLTU** [cosmo-11/seed-phrase-generator#1]
Why eset finding virus 10 second i launching application ?

**Comment by cosmo-11** [comment]
hi, perhaps due to large requests in blockchains in the program, the antivirus thinks that the program is a virus

**Comment by ReconLTU** [comment]
it writes what keyloger it is. your program generates keyloger

**Comment by cosmo-11** [comment]
This is a false positive. There are no viruses in the program, you can view the source code of the program and make sure of this, and you can also compile the program yourself using Visual Studio
